### ISSUE TITLE
hyrland.mhysa.conf correction

### ISSUE THREAD

**Issue by justinesmithies** [proycon/dotfiles#1]
Noticed in your [hyprland.mhysa.conf](https://github.com/proycon/dotfiles/blob/master/hypr/hyprland.mhysa.conf#L204) file at line 204 you have the following line:

`bind = $mainMod, a, togglespecialworkspace,`

I don't think there shouldn't be a comma at the end.

**Comment by proycon** [comment]
thanks...it does seem to work fine though, I use it all the time, the last column is reserved for an extra parameter usually, not sure if it's needed or not.
